import { Product, Category } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Beer', slug: 'beer', image: '/images/categories/beer.jpg' },
  { id: '2', name: 'Wine', slug: 'wine', image: '/images/categories/wine.jpg' },
  { id: '3', name: 'Whisky', slug: 'whisky', image: '/images/categories/whisky.jpg' },
  { id: '4', name: 'Vodka', slug: 'vodka', image: '/images/categories/vodka.jpg' },
  { id: '5', name: 'Rum', slug: 'rum', image: '/images/categories/rum.jpg' },
  { id: '6', name: 'Tequila', slug: 'tequila', image: '/images/categories/tequila.jpg' },
  { id: '7', name: 'Gin', slug: 'gin', image: '/images/categories/gin.jpg' },
  { id: '8', name: 'Brandy & Cognac', slug: 'brandy-cognac', image: '/images/categories/brandy.jpg' },
  { id: '9', name: 'Coolers & Ciders', slug: 'coolers-ciders', image: '/images/categories/coolers.jpg' },
  { id: '10', name: 'Spirits', slug: 'spirits', image: '/images/categories/spirits.jpg' },
  { id: '11', name: 'Sparkling', slug: 'sparkling', image: '/images/categories/sparkling.jpg' },
  { id: '12', name: 'Miscellaneous', slug: 'miscellaneous', image: '/images/categories/miscellaneous.jpg' },
];

export const defaultProducts: Product[] = [
  // === BEER ===
  {
    id: '1',
    name: 'Budweiser 24 Pack',
    price: 39.95,
    category: 'Beer',
    subcategory: 'Lager',
    country: 'Canada',
    size: '355ml x 24',
    type: 'Lager',
    image_url: '/images/products/budweiser-24.jpg',
    description: 'Classic Budweiser lager beer. Crisp, clean taste brewed with the best barley malt and a blend of premium hop varieties.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'Coors Light 12 Pack',
    price: 22.95,
    category: 'Beer',
    subcategory: 'Lager',
    country: 'Canada',
    size: '355ml x 12',
    type: 'Light Lager',
    image_url: '/images/products/coors-light-12.jpg',
    description: 'Cold filtered, cold packaged. The World\'s Most Refreshing Beer.',
    in_stock: true,
    featured: false,
    is_new: false,
    is_petrolia_pick: true,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '3',
    name: 'Molson Canadian 24 Pack',
    price: 38.95,
    category: 'Beer',
    subcategory: 'Lager',
    country: 'Canada',
    size: '355ml x 24',
    type: 'Lager',
    image_url: '/images/products/molson-canadian-24.jpg',
    description: 'A classic Canadian lager with a smooth, refreshing taste.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '4',
    name: 'Corona Extra 12 Pack',
    price: 26.95,
    category: 'Beer',
    subcategory: 'Lager',
    country: 'Mexico',
    size: '330ml x 12',
    type: 'Pale Lager',
    image_url: '/images/products/corona-12.jpg',
    description: 'A pilsner-style lager with a fruity-honey aroma and a touch of malt.',
    in_stock: true,
    featured: false,
    is_new: false,
    is_petrolia_pick: true,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '5',
    name: 'Heineken 12 Pack',
    price: 25.95,
    category: 'Beer',
    subcategory: 'Lager',
    country: 'Netherlands',
    size: '330ml x 12',
    type: 'Pale Lager',
    image_url: '/images/products/heineken-12.jpg',
    description: 'Premium quality lager with a mild bitter taste.',
    in_stock: true,
    featured: false,
    is_new: true,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-03-10',
  },
  {
    id: '6',
    name: 'Guinness Draught 8 Pack',
    price: 18.95,
    category: 'Beer',
    subcategory: 'Stout',
    country: 'Ireland',
    size: '440ml x 8',
    type: 'Stout',
    image_url: '/images/products/guinness-8.jpg',
    description: 'Rich, creamy stout with a distinctive dark colour and smooth taste.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },

  // === WINE ===
  {
    id: '7',
    name: 'Yellow Tail Shiraz',
    price: 12.95,
    category: 'Wine',
    subcategory: 'Red Wine',
    country: 'Australia',
    size: '750ml',
    type: 'Red',
    image_url: '/images/products/yellowtail-shiraz.jpg',
    description: 'Vibrant and smooth with berry and vanilla spice flavours. Perfect for any occasion.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '8',
    name: 'Kim Crawford Sauvignon Blanc',
    price: 18.95,
    category: 'Wine',
    subcategory: 'White Wine',
    country: 'New Zealand',
    size: '750ml',
    type: 'White',
    image_url: '/images/products/kim-crawford-sb.jpg',
    description: 'Fresh and vibrant with citrus and tropical fruit notes. Marlborough\'s finest.',
    in_stock: true,
    featured: false,
    is_new: false,
    is_petrolia_pick: true,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '9',
    name: 'Barefoot Moscato',
    price: 10.95,
    category: 'Wine',
    subcategory: 'White Wine',
    country: 'USA',
    size: '750ml',
    type: 'White',
    image_url: '/images/products/barefoot-moscato.jpg',
    description: 'Sweet and fruity with notes of peach, apricot and lemon zest.',
    in_stock: true,
    featured: false,
    is_new: true,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-03-15',
  },
  {
    id: '10',
    name: 'Meiomi Pinot Noir',
    price: 24.95,
    category: 'Wine',
    subcategory: 'Red Wine',
    country: 'USA',
    size: '750ml',
    type: 'Red',
    image_url: '/images/products/meiomi-pinot.jpg',
    description: 'Rich garnet, with lifted fruit aromas of bright strawberry and jammy fruit.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '11',
    name: 'Bottega Gold Prosecco',
    price: 29.95,
    category: 'Wine',
    subcategory: 'Sparkling Wine',
    country: 'Italy',
    size: '750ml',
    type: 'Sparkling',
    image_url: '/images/products/bottega-gold.jpg',
    description: 'Premium Italian Prosecco in a striking gold bottle. Light and fresh with apple and pear notes.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },

  // === WHISKY ===
  {
    id: '12',
    name: 'Jack Daniel\'s Old No. 7',
    price: 36.95,
    category: 'Whisky',
    subcategory: 'Tennessee Whiskey',
    country: 'USA',
    size: '750ml',
    type: 'Tennessee',
    image_url: '/images/products/jack-daniels.jpg',
    description: 'Smooth, full-bodied Tennessee whiskey. Charcoal mellowed for exceptional smoothness.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '37',
    name: 'Whyte & McKay Scotch 1.14L',
    price: 49.99,
    category: 'Whisky',
    subcategory: 'Scotch',
    country: 'Scotland',
    size: '1.14L',
    type: 'Scotch',
    image_url: '/images/products/whyte-mckay.jpg',
    description: 'Smooth Scotch Whisky from Whyte & McKay.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '38',
    name: 'St. Remy VSOP 750ml',
    price: 30.99,
    category: 'Brandy & Cognac',
    subcategory: 'Brandy',
    country: 'France',
    size: '750ml',
    type: 'VSOP',
    image_url: '/images/products/st-remy-vsop.jpg',
    description: 'Premium French Brandy.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },
  {
    id: '39',
    name: 'Cazadores Reposado Tequila 750ml',
    price: 49.99,
    category: 'Tequila',
    subcategory: 'Reposado',
    country: 'Mexico',
    size: '750ml',
    type: 'Reposado',
    image_url: '/images/products/cazadores-reposado.jpg',
    description: 'High-quality reposado tequila.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: false,
    created_at: '2024-01-01',
  },

  // === MISC / DONT FORGET ===
  {
    id: '40',
    name: 'Mr. & Mrs. T Margarita Mix 1L',
    price: 7.49,
    category: 'Miscellaneous',
    subcategory: 'Mixes',
    country: 'USA',
    size: '1L',
    type: 'Mixer',
    image_url: '/images/products/margarita-mix.jpg',
    description: 'Perfect for your favorite margaritas.',
    in_stock: true,
    featured: true,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: true,
    created_at: '2024-01-01',
  },
  {
    id: '41',
    name: 'Ice Bag 5lb',
    price: 4.49,
    category: 'Miscellaneous',
    subcategory: 'Ice',
    country: 'Canada',
    size: '5lb',
    type: 'Ice',
    image_url: '/images/products/ice-bag.jpg',
    description: 'Premium purified ice.',
    in_stock: true,
    featured: false,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: true,
    created_at: '2024-01-01',
  },
  {
    id: '42',
    name: 'Diet Coke 2L',
    price: 3.99,
    category: 'Miscellaneous',
    subcategory: 'Soda',
    country: 'Canada',
    size: '2L',
    type: 'Soda',
    image_url: '/images/products/diet-coke-2l.jpg',
    description: 'Classic Diet Coke.',
    in_stock: true,
    featured: false,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: true,
    created_at: '2024-01-01',
  },
  {
    id: '43',
    name: 'Petrolia Liquor Store Gift Card',
    price: 25.00,
    category: 'Miscellaneous',
    subcategory: 'Gift Cards',
    country: 'Canada',
    size: 'Variable',
    type: 'Gift Card',
    image_url: '/images/products/gift-card.jpg',
    description: 'Give the gift of choice.',
    in_stock: true,
    featured: false,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: true,
    created_at: '2024-01-01',
  },
  {
    id: '44',
    name: 'Cranberry Juice 1.89L',
    price: 8.99,
    category: 'Miscellaneous',
    subcategory: 'Juice',
    country: 'Canada',
    size: '1.89L',
    type: 'Juice',
    image_url: '/images/products/cranberry-juice.jpg',
    description: 'Perfect mixer for your cocktails.',
    in_stock: true,
    featured: false,
    is_new: false,
    is_petrolia_pick: false,
    is_miscellaneous: true,
    created_at: '2024-01-01',
  },
];

export const STORE_INFO = {
  name: 'Petrolia Liquor Store',
  phone: '+17804380448',
  phoneDisplay: '(780)-438-0448',
  address: '11431 40 Ave NW, Edmonton, AB T6J 0R4',
  hours: [
    { day: 'Mon - Thu', time: '10:00 AM - 10:00 PM' },
    { day: 'Fri - Sat', time: '10:00 AM - 11:00 PM' },
    { day: 'Sunday', time: '10:00 AM - 9:00 PM' },
  ],
  email: 'petrolialiquorstore@gmail.com',
  whatsapp: '+17804380448',
  socials: {
    facebook: 'https://www.facebook.com/petrolials',
    instagram: 'https://www.instagram.com/petrolialiquorstore/?hl=en'
  }
};
